// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLO0HK-F9-2BzP4T5478KTfSoYoZa7O-s',
    appId: '1:617709944602:web:c1abe0b074df33c4f476a3',
    messagingSenderId: '617709944602',
    projectId: 'app-meus-gastos',
    authDomain: 'app-meus-gastos.firebaseapp.com',
    storageBucket: 'app-meus-gastos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6y-fTP439QyqTqqXooHkuSHnsfDycH4',
    appId: '1:617709944602:android:325a73fbe9a91154f476a3',
    messagingSenderId: '617709944602',
    projectId: 'app-meus-gastos',
    storageBucket: 'app-meus-gastos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxpFBGJqZrc7qKkhhIDWFcKOzcF1KTDs',
    appId: '1:617709944602:ios:21eb8cdc00118026f476a3',
    messagingSenderId: '617709944602',
    projectId: 'app-meus-gastos',
    storageBucket: 'app-meus-gastos.appspot.com',
    iosBundleId: 'com.example.meusGastos',
  );
}
